Repository StampyAI/stampy, pull requests merged in 2023-06, with the labels that each got.

#247 only load modules in STAMPY_MODULES
  README.md
  config.py
  servicemodules/discord.py
  stam.py
  test/test_stam.py
Labels: enhancement

#226 Typing Stampy
  modules/duckduckgo.py
  utilities/discordutils.py
  utilities/flaskutils.py
  utilities/serviceutils.py
  utilities/slackutils.py
Labels: Big enhancement

#278 DiscordConstants (attempt number 2)
  .github/workflows/deploy-to-production-server.yml
  .github/workflows/unit-test-pull-request.yml
  README.md
  api/openai.py
  api/utilities/openai.py
  config.py
  environment.yml
  modules/Factoids.py
  modules/StampyControls.py
  modules/chatgpt.py
  modules/gpt3module.py
  requirements.txt
  scripts/notify-discord-stampy-offline.py
  scripts/update-stampy.sh
  servicemodules/discord.py
  servicemodules/discordConstants.py
  stam.py
  test/test_stam.py
  utilities/__init__.py
  utilities/discordutils.py
  utilities/utilities.py
Labels: Big enhancement

#280 discord channel id hotfix
  utilities/discordutils.py
Labels: bug, Top priority

#287 StampyControls/runstampy: STOP_ON_ERROR
  README.md
  modules/StampyControls.py
  runstampy
  stam.py
  utilities/utilities.py
Labels: enhancement

#285 Pylint in Dockerfile, testModule fix
  environment.yml
  modules/testModule.py
  requirements.txt
  runstampy
Labels: enhancement

#282 [bug] ddg: integration test
  modules/duckduckgo.py
Labels: bug

#290 [bug] reply/why: reference id
  modules/reply.py
  modules/why.py
Labels: bug, High priority

#293 various integration test fixes/disables
  modules/Factoids.py
  modules/chatgpt.py
  modules/gpt3module.py
  modules/sentience.py
  modules/stampcollection.py
Labels: bug

#291 Dockerfile: move to Alpine
  Dockerfile
Labels: enhancement

#296 [bug] question_setter: missing module name
  modules/question_setter.py
Labels: bug

#301 Configure Stampy's tendency to talk without being prompted
  README.md
  config.py
  modules/Random.py
  modules/Silly.py
  utilities/utilities.py
Labels: enhancement

#304 Channel whitelist (try 2)
  README.md
  config.py
  servicemodules/discord.py
Labels: enhancement

#305 HelpModule: case-insensitive
  modules/HelpModule.py
Labels: bug

#257 Proposal: `-Werror` in dev
  stam.py
Labels: enhancement, help wanted

#307 Typing fixes in config.py
  config.py
Labels: enhancement
