Repository StampyAI/stampy, pull requests merged in 2023-02, with the labels that each got.

#217 Added missing __str__ function in Eliza module.
  modules/Eliza.py
Labels: bug

#216 Add "Why did you say that?" To Stampy
  modules/module.py
  modules/why.py
  servicemodules/discord.py
  utilities/discordutils.py
  utilities/serviceutils.py
Labels: enhancement

#220 Fixing stampy providing the next question when not even remotely asked for it.
  modules/questions.py
Labels: bug, High priority

#222 remove old wiki
  .github/workflows/deploy-to-production-server.yml
  api/semanticwiki.py
  config.py
  get_all_wiki_pages.py
  load_wiki.py
  modules/reply.py
  modules/wikiUpdate.py
  runstampy
  servicemodules/discord.py
  test/api/__init__.py
  test/api/test_semanticwiki.py
  utilities/utilities.py
Labels: enhancement

#223 Fixed reloadallstamps command.
  .gitignore
  modules/stampcollection.py
  utilities/utilities.py
Labels: bug

#225 approval of reviews by @reviewers + fixed dedentation
  How to ask Stampy for questions.md
  modules/questions.py
Labels: Big enhancement
